/* Autogenerated with kurento-module-creator */

#ifndef __MNSCMIXER_IMPL_HPP__
#define __MNSCMIXER_IMPL_HPP__

#include "HubImpl.hpp"
#include "mnscmixer.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace mnscmixer
{
class mnscmixerImpl;
} /* mnscmixer */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::mnscmixer::mnscmixerImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace mnscmixer
{

class mnscmixerImpl : public HubImpl, public virtual mnscmixer
{

public:

  mnscmixerImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~mnscmixerImpl() = default;

  void focus(int sink_id, int param);

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* mnscmixer */
} /* module */
} /* kurento */

#endif /*  __MNSCMIXER_IMPL_HPP__ */
