/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "mnscmixerInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaPipeline.hpp"

namespace kurento
{
namespace module
{
namespace mnscmixer
{

void mnscmixerMethodFocus::invoke (std::shared_ptr<mnscmixer> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method mnscmixer::focus");
  }

  return obj->focus (sink_id, param);
}

void mnscmixerMethodFocus::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (sink_id);

    s.SerializeNVP (param);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

    if (!s.JsonValue.isMember ("sink_id") || !s.JsonValue["sink_id"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'sink_id' parameter should be a integer");
    }

    s.SerializeNVP (sink_id);

    if (!s.JsonValue.isMember ("param") || !s.JsonValue["param"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'param' parameter should be a integer");
    }

    s.SerializeNVP (param);

  }
}

std::shared_ptr<MediaPipeline> mnscmixerConstructor::getMediaPipeline ()
{
  return mediaPipeline;
}

void mnscmixerConstructor::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (mediaPipeline);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' should be an object");
    }

    if (!s.JsonValue.isMember ("mediaPipeline") || !s.JsonValue["mediaPipeline"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'mediaPipeline' parameter should be a string");
    }

    s.SerializeNVP (mediaPipeline);

  }
}

} /* mnscmixer */
} /* module */
} /* kurento */
