/* Autogenerated with kurento-module-creator */

#include "mnscmixer.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace mnscmixer
{

static std::vector<std::string> hierarchymnscmixer;
std::once_flag initFlagmnscmixer;

static void
initHierarchy ()
{
  hierarchymnscmixer.emplace_back("kurento.Hub");
  hierarchymnscmixer.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
mnscmixer::getHierarchy () const
{
  std::call_once (initFlagmnscmixer,initHierarchy);
  return hierarchymnscmixer;
}

const std::string&
mnscmixer::getType () const {
  static std::string typeName = "mnscmixer";

  return typeName;
}

const std::string&
mnscmixer::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
mnscmixer::getModule () const {
  static std::string moduleName =  "mnscmixer";

  return moduleName;
}

} /* mnscmixer */
} /* module */
} /* kurento */
