/* Autogenerated with kurento-module-creator */

#ifndef __MNSCMODULE_INTERNAL_HPP__
#define __MNSCMODULE_INTERNAL_HPP__

#include "mnscmodule.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace mnscmodule
{

class mnscmoduleConstructor
{
public:
  mnscmoduleConstructor() = default;
  ~mnscmoduleConstructor() = default;

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* mnscmodule */
} /* module */
} /* kurento */

#endif /*  __MNSCMODULE_INTERNAL_HPP__ */
