/* Autogenerated with kurento-module-creator */

#include "mnscmodule.hpp"
#include <mutex>

namespace kurento
{
namespace module
{
namespace mnscmodule
{

static std::vector<std::string> hierarchymnscmodule;
std::once_flag initFlagmnscmodule;

static void
initHierarchy ()
{
  hierarchymnscmodule.emplace_back("kurento.Filter");
  hierarchymnscmodule.emplace_back("kurento.MediaElement");
  hierarchymnscmodule.emplace_back("kurento.MediaObject");
}

const std::vector<std::string> &
mnscmodule::getHierarchy () const
{
  std::call_once (initFlagmnscmodule,initHierarchy);
  return hierarchymnscmodule;
}

const std::string&
mnscmodule::getType () const {
  static std::string typeName = "mnscmodule";

  return typeName;
}

const std::string&
mnscmodule::getQualifiedType () const {
  static std::string qualifiedTypeName = getModule() + "." + getType();

  return qualifiedTypeName;
}

const std::string&
mnscmodule::getModule () const {
  static std::string moduleName =  "mnscmodule";

  return moduleName;
}

} /* mnscmodule */
} /* module */
} /* kurento */
