/* Autogenerated with kurento-module-creator */

#ifndef __MNSCMIXER_IMPL_FACTORY_HPP__
#define __MNSCMIXER_IMPL_FACTORY_HPP__

#include "mnscmixerImpl.hpp"
#include "HubImplFactory.hpp"
#include <Factory.hpp>
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace mnscmixer
{

class mnscmixerImplFactory : public virtual HubImplFactory
{
public:
  mnscmixerImplFactory() = default;

  std::string getName() const override {
    return "mnscmixer";
  };

private:

  MediaObjectImpl *createObjectPointer (
      const boost::property_tree::ptree &conf,
      const Json::Value &params) const override;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* mnscmixer */
} /* module */
} /* kurento */

#endif /*  __MNSCMIXER_IMPL_FACTORY_HPP__ */
