/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include <mnscmoduleImplFactory.hpp>
#include "mnscmoduleImpl.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

#define GST_CAT_DEFAULT kurento_mnscmodule_impl
GST_DEBUG_CATEGORY_STATIC (GST_CAT_DEFAULT);
#define GST_DEFAULT_NAME "KurentomnscmoduleImpl"

namespace kurento
{
namespace module
{
namespace mnscmodule
{

mnscmoduleImpl::mnscmoduleImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) 
    : FilterImpl (config, std::dynamic_pointer_cast<MediaObjectImpl> (mediaPipeline)) 
{
  // TO-DO: Add implementation here
}

MediaObjectImpl *
mnscmoduleImplFactory::createObject (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline) const
{
  return new mnscmoduleImpl (config, mediaPipeline);
}

mnscmoduleImpl::StaticConstructor mnscmoduleImpl::staticConstructor;

mnscmoduleImpl::StaticConstructor::StaticConstructor()
{
  GST_DEBUG_CATEGORY_INIT (GST_CAT_DEFAULT, GST_DEFAULT_NAME, 0,
                           GST_DEFAULT_NAME);
}

} /* mnscmodule */
} /* module */
} /* kurento */
