/* Autogenerated with kurento-module-creator */

#ifndef __MNSCMODULE_IMPL_HPP__
#define __MNSCMODULE_IMPL_HPP__

#include "FilterImpl.hpp"
#include "mnscmodule.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace mnscmodule
{
class mnscmoduleImpl;
} /* mnscmodule */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::mnscmodule::mnscmoduleImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace mnscmodule
{

class mnscmoduleImpl : public FilterImpl, public virtual mnscmodule
{

public:

  mnscmoduleImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~mnscmoduleImpl() = default;

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* mnscmodule */
} /* module */
} /* kurento */

#endif /*  __MNSCMODULE_IMPL_HPP__ */
