/* Autogenerated with kurento-module-creator */

#ifndef __MNSCMODULE_HPP__
#define __MNSCMODULE_HPP__

#include <json/json.h>
#include <jsonrpc/JsonRpcException.hpp>
#include <memory>
#include <vector>
#include "Filter.hpp"

namespace kurento
{
namespace module
{
namespace mnscmodule
{
class mnscmodule;
} /* mnscmodule */
} /* module */
} /* kurento */

namespace kurento
{
class JsonSerializer;
void Serialize (std::shared_ptr<kurento::module::mnscmodule::mnscmodule> &object, JsonSerializer &serializer);
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace mnscmodule
{
class mnscmodule : public virtual Filter
{

public:
  mnscmodule() = default;
  ~mnscmodule() override = default;


  const std::string &getType() const override;
  const std::string &getQualifiedType() const override;
  const std::string &getModule() const override;
  const std::vector<std::string> &getHierarchy() const override;

  void Serialize(JsonSerializer &serializer) override = 0;

};

} /* mnscmodule */
} /* module */
} /* kurento */

#endif /*  __MNSCMODULE_HPP__ */
