/* Autogenerated with kurento-module-creator */

#include "mnscmoduleImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace mnscmodule
{

void dummyMnscmodule ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<mnscmodule> object;

    s.SerializeNVP (object);
  }
}

} /* mnscmodule */
} /* module */
} /* kurento */
