/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "mnscmixerImpl.hpp"
#include "mnscmixerImplFactory.hpp"
#include "mnscmixerInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace mnscmixer
{

MediaObjectImpl *mnscmixerImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  mnscmixerConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
mnscmixerImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "focus") {
    kurento::JsonSerializer s (false);
    mnscmixerMethodFocus method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<mnscmixer> (obj) );
    return;
  }

  HubImpl::invoke (obj, methodName, params, response);
}

bool
mnscmixerImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return HubImpl::connect (eventType, handler);
}

void
mnscmixerImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'mnscmixerImpl' cannot be deserialized as an object");
  }
}
} /* mnscmixer */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::mnscmixer::mnscmixerImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::mnscmixer::mnscmixerImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::mnscmixer::mnscmixerImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::mnscmixer::mnscmixer> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::mnscmixer::mnscmixerImpl> aux = std::dynamic_pointer_cast<kurento::module::mnscmixer::mnscmixerImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::mnscmixer::mnscmixer> (aux);
}

} /* kurento */