/* Autogenerated with kurento-module-creator */

#include "mnscmixerImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace mnscmixer
{

void dummyMnscmixer ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<mnscmixer> object;

    s.SerializeNVP (object);
  }
}

} /* mnscmixer */
} /* module */
} /* kurento */
